INSERT INTO songs (name, artist_id, album_id, audio)
VALUES
('Alone', 1, 1, 'https://jeffify.s3.amazonaws.com/alanwalker/faded/alone.mp3'),
('Faded', 1, 1, 'https://jeffify.s3.amazonaws.com/alanwalker/faded/faded.mp3'),
('Sing me to sleep', 1, 1, 'https://jeffify.s3.amazonaws.com/alanwalker/faded/singmetosleep.mp3'),
('The Spectre', 1, 1, 'https://jeffify.s3.amazonaws.com/alanwalker/faded/thespectre.mp3'),
('24k Magic', 2, 2, 'https://jeffify.s3.amazonaws.com/brunomars/24kmagic/24kmagic.mp3'),
('Finesse', 2, 2, 'https://jeffify.s3.amazonaws.com/brunomars/24kmagic/finesse.mp3'),
('Thats what I like', 2, 2, 'https://jeffify.s3.amazonaws.com/brunomars/24kmagic/thatswhatilike.mp3'),
('Versace on the floor', 2, 2, 'https://jeffify.s3.amazonaws.com/brunomars/24kmagic/versaceonthefloor.mp3'),
('Closer', 3, 3, 'https://jeffify.s3.amazonaws.com/chainsokers/collage/closer.mp3'),
('Dont let me down', 3, 3, 'https://jeffify.s3.amazonaws.com/chainsokers/collage/dontletmedown.mp3'),
('New York City', 3, 3, 'https://jeffify.s3.amazonaws.com/chainsokers/collage/newyorkcity.mp3'),
('Roses', 3, 3, 'https://jeffify.s3.amazonaws.com/chainsokers/collage/roses.mp3'),
('Something just like this', 3, 3, 'https://jeffify.s3.amazonaws.com/chainsokers/collage/somethingjustlikethis.mp3'),
('Until you were gone', 3, 3, 'https://jeffify.s3.amazonaws.com/chainsokers/collage/untilyouweregone.mp3'),
('Castle on a hill', 4, 4, 'https://jeffify.s3.amazonaws.com/edSheeran/divide/castleonahill.mp3'),
('Eraser', 4, 4, 'https://jeffify.s3.amazonaws.com/edSheeran/divide/eraser.mp3'),
('Galway girl', 4, 4, 'https://jeffify.s3.amazonaws.com/edSheeran/divide/galwaygirl.mp3'),
('Perfect', 4, 4, 'https://jeffify.s3.amazonaws.com/edSheeran/divide/perfect.mp3'),
('Shape of you', 4, 4, 'https://jeffify.s3.amazonaws.com/edSheeran/divide/shapeofyou.mp3'),
('25 to life', 5, 5, 'https://jeffify.s3.amazonaws.com/eminem/recovery/25tolife.mp3'),
('Almost famous', 5, 5, 'https://jeffify.s3.amazonaws.com/eminem/recovery/almostfamous.mp3'),
('Cinderella Man', 5, 5, 'https://jeffify.s3.amazonaws.com/eminem/recovery/cinderellaman.mp3'),
('Love the way you lie', 5, 5, 'https://jeffify.s3.amazonaws.com/eminem/recovery/lovethewayyoulie.mp3'),
('Not afraid', 5, 5, 'https://jeffify.s3.amazonaws.com/eminem/recovery/notafraid.mp3'),
('On fire', 5, 5, 'https://jeffify.s3.amazonaws.com/eminem/recovery/onfire.mp3'),
('Seduction', 5, 5, 'https://jeffify.s3.amazonaws.com/eminem/recovery/seduction.mp3'),
('Spacebound', 5, 5, 'https://jeffify.s3.amazonaws.com/eminem/recovery/spacebound.mp3'),
('Bleeding out', 6, 6, 'https://jeffify.s3.amazonaws.com/imaginedragons/nightvisions/bleedingout.mp3'),
('Demons', 6, 6, 'https://jeffify.s3.amazonaws.com/imaginedragons/nightvisions/demons.mp3'),
('Its time', 6, 6, 'https://jeffify.s3.amazonaws.com/imaginedragons/nightvisions/itstime.mp3'),
('Radioactive', 6, 6, 'https://jeffify.s3.amazonaws.com/imaginedragons/nightvisions/radioactive.mp3'),
('Company', 7, 7, 'https://jeffify.s3.amazonaws.com/justin_bieber/purpose/company.mp3'),
('Love yourself', 7, 7, 'https://jeffify.s3.amazonaws.com/justin_bieber/purpose/loveyourself.mp3'),
('Mark my words', 7, 7, 'https://jeffify.s3.amazonaws.com/justin_bieber/purpose/markmywords.mp3'),
('Purpose', 7, 7, 'https://jeffify.s3.amazonaws.com/justin_bieber/purpose/purpose.mp3'),
('Sorry', 7, 7, 'https://jeffify.s3.amazonaws.com/justin_bieber/purpose/sorry.mp3'),
('What do you mean', 7, 7, 'https://jeffify.s3.amazonaws.com/justin_bieber/purpose/whatdoyoumean.mp3'),
('Daylight', 8, 8, 'https://jeffify.s3.amazonaws.com/maroon5/overexposed/daylight.mp3'),
('Love somebody', 8, 8, 'https://jeffify.s3.amazonaws.com/maroon5/overexposed/lovesomebody.mp3'),
('One more night', 8, 8, 'https://jeffify.s3.amazonaws.com/maroon5/overexposed/onemorenight.mp3'),
('Payphone', 8, 8, 'https://jeffify.s3.amazonaws.com/maroon5/overexposed/payphone.mp3'),
('She will be loved', 8, 9, 'https://jeffify.s3.amazonaws.com/maroon5/songsaboutjane/shewillbeloved.mp3'),
('Sunday morning', 8, 9, 'https://jeffify.s3.amazonaws.com/maroon5/songsaboutjane/sundaymorning.mp3'),
('This love', 8, 9, 'https://jeffify.s3.amazonaws.com/maroon5/songsaboutjane/thislove.mp3'),
('Animals', 8, 10, 'https://jeffify.s3.amazonaws.com/maroon5/V/animals.mp3'),
('Lost stars', 8, 10, 'https://jeffify.s3.amazonaws.com/maroon5/V/loststars.mp3'),
('Maps', 8, 10, 'https://jeffify.s3.amazonaws.com/maroon5/V/maps.mp3'),
('Sugar', 8, 10, 'https://jeffify.s3.amazonaws.com/maroon5/V/sugar.mp3'),
('Death of a bachelor', 9, 11, 'https://jeffify.s3.amazonaws.com/PATD/deathofbachelor/deathofabachelor.mp3'),
('Dont threaten me with a good time', 9, 11, 'https://jeffify.s3.amazonaws.com/PATD/deathofbachelor/dontthreatenmewithagoodtime.mp3'),
('Emperors new clothes', 9, 11, 'https://jeffify.s3.amazonaws.com/PATD/deathofbachelor/emperorsnewclothes.mp3'),
('The good, the bad, and the dirty', 9, 11, 'https://jeffify.s3.amazonaws.com/PATD/deathofbachelor/thegoodthebadnadthedirty.mp3'),
('Victorious', 9, 11, 'https://jeffify.s3.amazonaws.com/PATD/deathofbachelor/victorious.mp3'),
('Dying in LA', 9, 12, 'https://jeffify.s3.amazonaws.com/PATD/prayforthewicked/dyinginla.mp3'),
('High hopes', 9, 12, 'https://jeffify.s3.amazonaws.com/PATD/prayforthewicked/highhopes.mp3'),
('Say Amen', 9, 12, 'https://jeffify.s3.amazonaws.com/PATD/prayforthewicked/sayamen.mp3'),
('Im not the only one', 10, 13, 'https://jeffify.s3.amazonaws.com/samsmith/inthelonelyhour/imnottheonlyone.mp3'),
('Lay me down', 10, 13, 'https://jeffify.s3.amazonaws.com/samsmith/inthelonelyhour/laymedown.mp3'),
('Stay with me', 10, 13, 'https://jeffify.s3.amazonaws.com/samsmith/inthelonelyhour/staywithme.mp3'),
('Too good at goodbyes', 10, 14, 'https://jeffify.s3.amazonaws.com/samsmith/thethrillofitall/toogoodatgoodbyes.mp3'),
('All you had to do was stay', 11, 15, 'https://jeffify.s3.amazonaws.com/taylor_swift/1989/allyouhadtodowasstay.mp3'),
('Bad blood', 11, 15, 'https://jeffify.s3.amazonaws.com/taylor_swift/1989/badblood.mp3'),
('Blank space', 11, 15, 'https://jeffify.s3.amazonaws.com/taylor_swift/1989/blankspace.mp3'),
('Shake it off', 11, 15, 'https://jeffify.s3.amazonaws.com/taylor_swift/1989/shakeitoff.mp3'),
('Style', 11, 15, 'https://jeffify.s3.amazonaws.com/taylor_swift/1989/style.mp3'),
('Wildest dreams', 11, 15, 'https://jeffify.s3.amazonaws.com/taylor_swift/1989/wildestdreams.mp3'),
('22', 11, 16, 'https://jeffify.s3.amazonaws.com/taylor_swift/red/22.mp3'),
('Everything has changed', 11, 16, 'https://jeffify.s3.amazonaws.com/taylor_swift/red/everythinghaschanged.mp3'),
('I knew you were trouble', 11, 16, 'https://jeffify.s3.amazonaws.com/taylor_swift/red/iknewyouweretrouble.mp3'),
('Red', 11, 16, 'https://jeffify.s3.amazonaws.com/taylor_swift/red/red.mp3');










INSERT INTO albums (name, artist_id, image, year)
VALUES
('Faded',1 , 'https://upload.wikimedia.org/wikipedia/en/d/da/Alan_Walker_-_Faded.png', 2014),
('24k Magic',2 , 'https://upload.wikimedia.org/wikipedia/en/2/2b/Bruno_Mars_-_24K_Magic_%28Official_Album_Cover%29.png', 2016),
('Collage', 3, 'https://upload.wikimedia.org/wikipedia/en/2/22/Collage%2C_album_cover.jpg', 2017),
('÷',4 , 'https://upload.wikimedia.org/wikipedia/en/4/45/Divide_cover.png', 2017),
('Recovery', 5, 'https://upload.wikimedia.org/wikipedia/en/6/60/Recovery_Album_Cover.jpg', 2010),
('Night Visions', 6, 'https://upload.wikimedia.org/wikipedia/en/3/3f/Night_Visions_Album_Cover.jpeg', 2012),
('Purpose', 7, 'https://upload.wikimedia.org/wikipedia/en/2/27/Justin_Bieber_-_Purpose_%28Official_Album_Cover%29.png', 2015),
('Overexposed', 8, 'https://upload.wikimedia.org/wikipedia/en/7/77/Maroon_5_-_Overexposed.png', 2012),
('Songs About Jane', 8, 'https://upload.wikimedia.org/wikipedia/en/b/be/Maroon_5_-_Songs_About_Jane.png', 2002),
('V', 8, 'https://upload.wikimedia.org/wikipedia/en/5/53/Maroon_5_-_V_%28Official_Album_Cover%29.png', 2014),
('Death of a Bachelor', 9, 'https://upload.wikimedia.org/wikipedia/en/e/e4/Death_of_a_Bachelor.jpg', 2016),
('Pray for the wicked', 9, 'https://upload.wikimedia.org/wikipedia/en/5/5d/PATD_PFTW.jpg', 2016),
('In the lonely hour', 10, 'https://upload.wikimedia.org/wikipedia/en/9/99/Sam_Smith_-_In_the_Lonely_Hour_%28Official_Album_Cover%29.png', 2014),
('The thrill of it all', 10, 'https://upload.wikimedia.org/wikipedia/en/6/67/SamSmithThrillOfItAll.png', 2017),
('1989', 11, 'https://upload.wikimedia.org/wikipedia/en/f/f6/Taylor_Swift_-_1989.png', 2014),
('Red', 11, 'https://upload.wikimedia.org/wikipedia/en/e/e8/Taylor_Swift_-_Red.png', 2012);


INSERT INTO artists (name, image)
VALUES
('Alan Walker', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Alan_Walker_Pressphoto.jpg/800px-Alan_Walker_Pressphoto.jpg'),
('Bruno Mars', 'https://upload.wikimedia.org/wikipedia/commons/b/b0/BrunoMars24KMagicWorldTourLive_%28cropped%29.jpg'),
('Chainsmokers','https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/The_Chainsmokers_in_interview_2015.png/1280px-The_Chainsmokers_in_interview_2015.png'),
('Ed Sheeran','https://upload.wikimedia.org/wikipedia/commons/c/c1/Ed_Sheeran-6886_%28cropped%29.jpg'),
('Eminem','https://upload.wikimedia.org/wikipedia/commons/4/4a/Eminem_-_Concert_for_Valor_in_Washington%2C_D.C._Nov._11%2C_2014_%282%29_%28Cropped%29.jpg'),
('Imagine Dragons','https://upload.wikimedia.org/wikipedia/commons/0/04/Imagine_Dragons%2C_Roundhouse%2C_London_%2835390234536%29.jpg'),
('Justin Bieber','https://upload.wikimedia.org/wikipedia/commons/d/da/Justin_Bieber_in_2015.jpg'),
('Maroon 5','https://upload.wikimedia.org/wikipedia/commons/d/d9/Maroon_5_performing_in_Sydney.jpg'),
('Panic! At The Disco','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Panic_at_the_Disco_Im_Park_2016_%2811_von_11%29.jpg/800px-Panic_at_the_Disco_Im_Park_2016_%2811_von_11%29.jpg'),
('Sam Smith','https://upload.wikimedia.org/wikipedia/commons/0/0c/Sam_Smith_Lollapalooza_2015-9_%28cropped%29.jpg'),
('Taylor Swift','https://upload.wikimedia.org/wikipedia/commons/b/b5/191125_Taylor_Swift_at_the_2019_American_Music_Awards_%28cropped%29.png')
